### ISSUE TITLE
Substitute bullet files of Urho3D master with yours? 

### ISSUE THREAD

**Issue by sirop** [Lumak/Urho3D-Offroad-Vehicle#1]
Hello.

Just tried to build this repo,
but did not subsitute, for instance, UrHo3D's _btWheelInfo.h_ with _btWheelInfo.h_ of this repo.

Therefore some errors https://gist.github.com/sirop/6f2bc9d7c29249723a9f6357d999c921 .

If your __btWheelInfo.h_  is ewer (and better?), why is it not in the master branch of Urho3D?

Thanks.

**Comment by Lumak** [comment]
There are a couple new variables defined in my repo in the btWheelInfo.h:
```
    // Lumak: member vars added
    btScalar    m_sideFrictionStiffness;
    btScalar    m_skidInfoCumulative;

```
Which are required to achieve the type of vehicle dynamic that I try to achieve, and without it you'll get errors.
